300
# Weilei Zeng
# 20circuit tom XXX XXX in shor'scode
# There are three versions of thiscircuit 1>standard one 2>simplified one 3>more simplified
# Here shows 1>the standard one

 H 200
c 200 0
c 200 1
c 200 2
c 200 3
c 200 4
c 200 5
 H 200
m 0 200 
#For the last part in this file, manually change the classical bit for saving measurement result. (following example in conv5v5v2.qc). The sequence is also writen in conv5.txt. conv7 use the same sequence.
